### ISSUE TITLE
How can I get the dataset like nell/nell-1.tns.gz?

### ISSUE THREAD

**Issue by tanghao123th** [frostt-tensor/frostt-tensor.github.io#13]
How can I get the dataset like nell/nell-1.tns.gz?

**Comment by jeewhanchoi** [comment]
Please go to http://frostt.io and download it from there

**Comment by tanghao123th** [comment]
Received.Thangk you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frostt-tensor/frostt-tensor.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 中午11:49
收件人:&nbsp;"frostt-tensor/frostt-tensor.github.io"<frostt-tensor.github.io@noreply.github.com&gt;;
抄送:&nbsp;"86182296"<86182296@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [frostt-tensor/frostt-tensor.github.io] How can I get the dataset like nell/nell-1.tns.gz? (#13)





 
Please go to http://frostt.io and download it from there
